t = input("Введите значение t: ")
v = input("Введите значение v: ")
x = input("Введите значение x: ")
y = input("Введите значение y: ")
print("a) 5 10")
print("b) 100", t)
print("c)", x, "25")
print("d)", x, y)
print()
print("7 см")
print("1949", v)
