a = input("Введите значение a: ")
b = input("Введите значение b: ")
x = input("Введите значение x: ")
y = input("Введите значение y: ")
print("a) 2 кг")
print("b)", a, "1")
print("c)", x, y)
print("d)", x, y)
print()
print("13 17")
print("19", b)
print("5", y)
