h = int(input("Часы (0 < h ≤ 23): "))
m = int(input("Минуты (0 ≤ m ≤ 59): "))
s = int(input("Секунды (0 ≤ s ≤ 59): "))
angle = h * 30 + m * 0.5 + s * (0.5 / 60)
print(f"Угол часовой стрелки: {angle:.2f}°")
