a = float(input("Размер форточки a (см) = "))
b = float(input("Размер форточки b (см) = "))
d = float(input("Диаметр головы (см) = "))
fit = (d + 2 <= a) and (d + 2 <= b)
print("Голова пролезет:", fit)
