print("Введите возраст 20 учеников первого класса (в годах, через пробел):")
ages1 = list(map(float, input().split()[:20]))
print("Введите возраст 20 учеников второго класса (в годах, через пробел):")
ages2 = list(map(float, input().split()[:20]))
avg1 = sum(ages1) / len(ages1)
avg2 = sum(ages2) / len(ages2)
print(f"Средний возраст в первом классе: {avg1:.2f} лет")
print(f"Средний возраст во втором классе: {avg2:.2f} лет")
