n = int(input("Введите количество чисел n: "))
numbers = list(map(int, input(f"Введите {n} целых чисел через пробел: ").split()[:n]))
p = int(input("Введите число p: "))
count_gt_p = sum(1 for x in numbers if x > p)
print(f"а) Количество чисел > {p}: {count_gt_p}")
count_ends_5 = sum(1 for x in numbers if x % 10 == 5)
print(f"б) Количество чисел, оканчивающихся на 5: {count_ends_5}")
k = int(input("Введите число k: "))
count_mult_k = sum(1 for x in numbers if x % k == 0)
print(f"в) Количество чисел, кратных {k}: {count_mult_k}")
