n = int(input("Введите количество учеников: "))
grades = list(map(int, input("Введите оценки через пробел: ").split()[:n]))
count_5 = grades.count(5)
count_4 = grades.count(4)
count_3 = grades.count(3)
count_2 = grades.count(2)
print(f"Пятёрок: {count_5}")
print(f"Четвёрок: {count_4}")
print(f"Троек: {count_3}")
print(f"Двоек: {count_2}")
